channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pip
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - absl-py=0.11.0=py38h578d9bd_0
  - argon2-cffi=20.1.0=py38h7b6447c_1
  - async_generator=1.10=py_0
  - attrs=20.2.0=py_0
  - backcall=0.2.0=py_0
  - blas=1.0=mkl
  - bleach=3.2.1=py_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.17.1=h36c2ea0_0
  - ca-certificates=2021.1.19=h06a4308_0
  - cairo=1.14.12=h8948797_3
  - certifi=2020.12.5=py38h06a4308_0
  - cffi=1.14.3=py38he30daa8_0
  - cloudpickle=1.6.0=py_0
  - cudatoolkit=11.0.221=h6bb024c_0
  - curl=7.68.0=hf8cf82a_0
  - cycler=0.10.0=py38_0
  - cython=0.29.21=py38h348cfbe_1
  - dbus=1.13.16=hb2f20db_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py38_0
  - expat=2.2.9=he6710b0_2
  - ffmpeg=4.2.2=h20bf706_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.2=h5ab3b9f_0
  - freexl=1.0.5=h14c3975_0
  - future=0.18.2=py38h578d9bd_2
  - gdal=2.3.3=py38hbb2a789_0
  - geos=3.7.1=he6710b0_0
  - giflib=5.1.4=h14c3975_1
  - glib=2.65.0=h3eb4bd4_0
  - gmp=6.1.2=h6c8ec71_1
  - gnutls=3.6.5=h71b1129_1002
  - grpcio=1.33.2=py38heead2fc_2
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=he6710b0_3
  - importlib-metadata=1.7.0=py38_0
  - importlib_metadata=1.7.0=0
  - intel-openmp=2020.2=254
  - ipykernel=5.3.4=py38h5ca1d4c_0
  - ipython=7.18.1=py38h5ca1d4c_0
  - ipython_genutils=0.2.0=py38_0
  - ipywidgets=7.5.1=py_1
  - isort=5.6.4=py_0
  - jedi=0.17.2=py38_0
  - jinja2=2.11.2=py_0
  - jpeg=9b=h024ee3a_2
  - json-c=0.13.1=h1bed415_0
  - jsonschema=3.2.0=py38_1
  - jupyter=1.0.0=py38_7
  - jupyter_client=6.1.7=py_0
  - jupyter_console=6.2.0=py_0
  - jupyter_core=4.6.3=py38_0
  - jupyterlab_pygments=0.1.2=py_0
  - kealib=1.4.7=hd0c454d_6
  - kiwisolver=1.2.0=py38hfd86e86_0
  - krb5=1.16.4=h173b8e3_0
  - lame=3.100=h7b6447c_0
  - lazy-object-proxy=1.4.3=py38h7b6447c_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libboost=1.67.0=h46d08c1_4
  - libcurl=7.68.0=hda55be3_0
  - libdap4=3.19.1=h6ec2957_0
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgdal=2.3.3=h2e7e64b_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.15=h63c8f33_5
  - libkml=1.3.0=h590aaf7_4
  - libnetcdf=4.6.1=h11d0813_2
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libpq=11.5=hd9ab2ff_2
  - libprotobuf=3.13.0.1=hd408876_0
  - libsodium=1.0.18=h7b6447c_0
  - libspatialite=4.3.0a=hb08deb6_19
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libuv=1.40.0=h7b6447c_0
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=he19cac6_1
  - lz4-c=1.9.2=he6710b0_1
  - markdown=3.3.3=pyh9f0ad1d_0
  - markupsafe=1.1.1=py38h7b6447c_0
  - matplotlib=3.3.1=0
  - matplotlib-base=3.3.1=py38h817c723_0
  - mccabe=0.6.1=py38_1
  - mistune=0.8.4=py38h7b6447c_1000
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.2.0=py38h23d657b_0
  - mkl_random=1.1.1=py38h0573a6f_0
  - nbclient=0.5.0=py_0
  - nbconvert=6.0.7=py38_0
  - nbformat=5.0.7=py_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.4.1=py_0
  - nettle=3.4.1=hbb512f6_0
  - ninja=1.10.2=py38hff7bd54_0
  - notebook=6.1.4=py38_0
  - numpy=1.19.1=py38hbc911f0_0
  - numpy-base=1.19.1=py38hfa32c7d_0
  - olefile=0.46=py_0
  - openh264=2.1.0=hd408876_0
  - openjpeg=2.3.0=h05c96fa_1
  - openssl=1.1.1i=h27cfd23_0
  - packaging=20.4=py_0
  - pandoc=2.10.1=0
  - pandocfilters=1.4.2=py38_1
  - parso=0.7.0=py_0
  - pcre=8.44=he6710b0_0
  - pexpect=4.8.0=py38_0
  - pickleshare=0.7.5=py38_1000
  - pillow=7.2.0=py38hb39fc2d_0
  - pixman=0.40.0=h7b6447c_0
  - poppler=0.65.0=h581218d_1
  - poppler-data=0.4.10=h06a4308_0
  - portalocker=1.7.0=py38h32f6830_1
  - proj4=5.2.0=he6710b0_1
  - prometheus_client=0.8.0=py_0
  - prompt-toolkit=3.0.7=py_0
  - prompt_toolkit=3.0.7=0
  - protobuf=3.13.0.1=py38he6710b0_1
  - ptyprocess=0.6.0=py38_0
  - pycocotools=2.0.2=py38h1e0a361_1
  - pycparser=2.20=py_2
  - pydot=1.2.4=py_0
  - pygments=2.7.1=py_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py38h05f1152_4
  - pyrsistent=0.17.3=py38h7b6447c_0
  - python=3.8.5=h7579374_1
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytorch=1.7.1=py3.8_cuda11.0.221_cudnn8.0.5_0
  - pyyaml=5.3.1=py38h8df0ef7_1
  - qt=5.9.7=h5867ecd_1
  - qtconsole=4.7.7=py_0
  - qtpy=1.9.0=py_0
  - readline=8.0=h7b6447c_0
  - send2trash=1.5.0=py38_0
  - setuptools=50.3.0=py38hb0f4dca_1
  - sip=4.19.13=py38he6710b0_0
  - six=1.15.0=py_0
  - sqlite=3.33.0=h62c20be_0
  - tabulate=0.8.7=pyh9f0ad1d_0
  - tensorboard=1.15.0=py38_0
  - termcolor=1.1.0=py_2
  - terminado=0.8.3=py38_0
  - testpath=0.4.4=py_0
  - toml=0.10.1=py_0
  - torchvision=0.8.2=py38_cu110
  - tornado=6.0.4=py38h7b6447c_1
  - tqdm=4.54.1=pyhd8ed1ab_1
  - traitlets=5.0.4=py38_0
  - typing_extensions=3.7.4.3=py_0
  - tzdata=2021a=h5d7bf9c_0
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py38_1
  - werkzeug=1.0.1=pyh9f0ad1d_0
  - wheel=0.35.1=py_0
  - widgetsnbextension=3.5.1=py38_0
  - wrapt=1.11.2=py38h7b6447c_0
  - x264=1!157.20191217=h7b6447c_0
  - xerces-c=3.2.3=h780794e_0
  - xz=5.2.5=h7b6447c_0
  - yacs=0.1.6=py_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.2=he6710b0_3
  - zipp=3.3.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - affine==2.3.0
    - alembic==1.4.1
    - antlr4-python3-runtime==4.8
    - appdirs==1.4.4
    - av==8.0.3
    - azure-core==1.9.0
    - azure-storage-blob==12.6.0
    - black==21.4b2
    - click==7.1.2
    - click-plugins==1.1.1
    - cligj==0.7.1
    - cryptography==3.3.1
    - databricks-cli==0.14.1
    - docker==4.4.0
    - filterpy==1.4.5
    - flask==1.1.2
    - fvcore==0.1.5.post20211019
    - gitdb==4.0.5
    - gitpython==3.1.11
    - gunicorn==20.0.4
    - hydra-core==1.1.1
    - idna==2.10
    - imageio==2.9.0
    - imantics==0.1.12
    - importlib-resources==5.3.0
    - iniconfig==1.1.1
    - iopath==0.1.8
    - isodate==0.6.0
    - itsdangerous==1.1.0
    - joblib==1.1.0
    - jupyter-notebookparams==0.0.4
    - lxml==4.6.1
    - mako==1.1.3
    - mlflow==1.12.1
    - mock==4.0.3
    - motmetrics==1.2.0
    - msrest==0.6.19
    - mypy-extensions==0.4.3
    - networkx==2.5
    - oauthlib==3.1.0
    - omegaconf==2.1.1
    - opencv-contrib-python==4.5.1.48
    - opencv-python==4.5.1.48
    - pandas==1.1.5
    - pathspec==0.9.0
    - pip==20.3
    - pip-licenses==3.5.3
    - pluggy==0.13.1
    - prometheus-flask-exporter==0.18.1
    - ptable==0.9.2
    - py==1.10.0
    - py-cpuinfo==7.0.0
    - pycodestyle==2.6.0
    - pyflakes==2.2.0
    - pykalman==0.9.5
    - pyproj==3.0.1
    - pytest==6.2.1
    - pytest-benchmark==3.2.3
    - python-editor==1.0.4
    - pytz==2020.4
    - pywavelets==1.1.1
    - querystring-parser==1.2.4
    - rasterio==1.1.8
    - regex==2021.10.8
    - requests==2.24.0
    - requests-oauthlib==1.3.0
    - scikit-image==0.18.1
    - scikit-learn==0.22.2
    - scipy==1.7.1
    - shapely==1.7.1
    - smmap==3.0.4
    - snuggs==1.4.7
    - sqlalchemy==1.3.20
    - sqlparse==0.4.1
    - tifffile==2021.1.14
    - tk==0.1.0
    - urllib3==1.25.10
    - websocket-client==0.57.0
    - xmljson==0.2.1
    - xmltodict==0.12.0
